apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "3000"
  MONGO_HOST: "mongodb-service"
  MONGO_DB: "shopdb"
immutable: true   ##  prevent the data in backend-config from being changed.